#已设置logback策略,基础日志配置不用了
#logging:
#  level: 
#    com.leo.nas.coin: debug #设置包级别的日志
    
server:
  port: 8080 
  servlet:
    context-path: /nas
    
coin: 
   shortName: NAS01   
   name: Nebula
   zhName: 星云链test
   icoPrice: 14
   icoTotal: 10000000
   